# Generated by Django 3.0.6 on 2020-05-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='num_passengers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
