# Generated by Django 3.0.6 on 2020-05-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_travel_num_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='country',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='travel',
            name='destination',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='travel',
            name='source',
            field=models.CharField(max_length=60),
        ),
    ]
