# Generated by Django 3.0.6 on 2020-05-31 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
